name: "Deploy Aerolab Cluster"
description: "Creates an Aerospike cluster using Aerolab on the current runner"

inputs:
  aerospike_version:
    description: "Aerospike version for cluster creation"
    required: false
    default: "8.1.0.1"
  nodes:
    description: "Number of cluster nodes"
    required: false
    default: "3"
  cluster_name:
    description: "Cluster name"
    required: false
    default: "ce"

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Download Aerolab .deb
      shell: bash
      run: |
        echo "Downloading Aerolab 7.9.0 (amd64)"
        curl -L -o aerolab.deb https://github.com/aerospike/aerolab/releases/download/7.9.0/aerolab-linux-amd64-7.9.0.deb

    - name: Install Aerolab
      shell: bash
      run: |
        sudo dpkg -i aerolab.deb
        sudo apt-get install -f -y

    - name: Prepare Aerolab home
      shell: bash
      run: |
        mkdir -p /tmp/aerolab-home
        echo "AEROLAB_HOME=/tmp/aerolab-home" >> $GITHUB_ENV

    - name: Configure Aerolab backend
      shell: bash
      run: |
        aerolab config backend -t docker

    - name: Create Aerospike cluster
      shell: bash
      run: |
        aerolab cluster create \
          -v "${{ inputs.aerospike_version }}" \
          -c "${{ inputs.nodes }}" \
          -n "${{ inputs.cluster_name }}"

    - name: Validate cluster list
      shell: bash
      run: |
        echo "Listing clusters..."
        aerolab cluster list | tee cluster-list.txt

    - name: Show cluster list output as job summary
      shell: bash
      run: |
        echo "## Aerolab Cluster Created" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '````' >> $GITHUB_STEP_SUMMARY
        cat cluster-list.txt >> $GITHUB_STEP_SUMMARY
        echo '````' >> $GITHUB_STEP_SUMMARY
